config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/events',  to: 'static_pages#events',  via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save :prepare_name_for_db
	before_create :create_remember_token

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates 	:name, presence:true, length: { maximum: 50 }, 
				uniqueness: { case_sensitive: false }
	
    validates 	:email, allow_blank:true, format: { with: VALID_EMAIL_REGEX  }

    validates	:password, length: { minimum: 6 }

    has_secure_password

    def User.create_token
		SecureRandom::urlsafe_base64
	end

	def User.hash_token(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def prepare_name_for_db
			self.name = name.downcase
		end

		def create_remember_token
			self.remember_token = User.hash_token(User.create_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		# nothing to do here, other than render the page? ok!
	end

	def create
		@user = User.find_by_name(params[:session][:name].downcase)
		if @user && @user.authenticate(params[:session][:password])
			flash.now[:success] = "Welcome back."
			signin_user(@user)
			redirect_back_or @user 		# polymorphism? it knows where to go for some reason
		else
			flash.now[:danger] = "Display Name and/or Password incorrect."
			render 'new'
		end
	end

	def destroy
		sign_out
		flash[:info] = "Successfully signed out."
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def events
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_out_user, only: [:new, :create]
  before_action :signed_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def new
  	@user = User.new
  end

  def index
    @users = User.paginate(page: params[:page])
    @count = User.count
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      signin_user(@user)
      flash[:success] = "Welcome to the thing."
  		redirect_to @user # equivalent to user_path(@user.id)
  	else
  		render 'new'		
  	end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash.now[:success] = "Profile updated."
      render 'show'
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user == current_user
      redirect_to root_url
    else
      @user.destroy
      flash[:success] = "Deleted."
      redirect_to users_path
    end
  end



  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    #Before filters

    def signed_out_user
      if signed_in?
        redirect_to root_url
      end
    end

    def signed_in_user
      if !signed_in?
        flash[:info] = "Please sign in."
        store_location
        redirect_to signin_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      if @user != current_user
        redirect_to root_url
      end
    end

    def admin_user
      redirect_to root_url unless current_user.admin?
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	def gravatar_for(user, options = { size:80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		return image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def signin_user(user)
		remember_token = User.create_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.hash_token(remember_token))
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		hashed_token = User.hash_token(cookies[:remember_token])
		@current_user ||= User.find_by(:remember_token => hashed_token)
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.hash_token(User.create_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |status, msg| %>
	<%= content_tag(:div, class: "alert alert-#{status} alert-dismissable") do -%>
		<%= msg %>
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<% end -%>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Announciator", root_path %>
    by Danny
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Influencr", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right nav-pills">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Help",    help_path %></li>
              <li><%= link_to "Events",  events_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Sign out", signout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/_signup_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-danger alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

		That didn't work. <%= pluralize(@user.errors.count, "problem") %>:
		
		<% @user.errors.full_messages.each do |error| %>
			<ul>
				<li><%= error %></li>
			</ul>
		<% end %>
	</div>
</div>
<% end %>

app/views/layouts/_top_post.html.erb
<div class="container">
	<h4>Here's what we're paying attention to right now. Most popular announcement:</h3>
	<div class="center hero-unit popular">
		<h3>This site is awesome!</h3>
		<h2>Posted by 
			<% if signed_in? %>
				<%= current_user.name %> 
			<% else %>
				Some guy
			<% end %>
			at <%= Date.new(2014,4,10) %>
		</h2>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/flash' %>
<%= yield %>
<%= render 'layouts/footer' %>

<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>This is the about page.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>
<p>This is the contact page.</p>

app/views/static_pages/events.html.erb
<% provide(:title, "Events") %>
<h1>Events</h1>
<p>This is the events page.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>This is the help page</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Influencr</h1>

  <h2>Say something and see who pays attention!</h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<%= render 'layouts/top_post' %>

app/views/users/_user.html.erb
<li>
	<%= link_to(user.name, user) %>
	<%= gravatar_for user %>
	<% if current_user.admin? && !current_user?(user) %>
		 | <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" } %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for @user do |f| %>
			<%= render 'layouts/signup_error_messages' %>

			<%= f.label :name, "Display Name" %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save changes", class: "btn btn-large btn-info signup" %>

		<% end %>

		<%= gravatar_for(@user) %>
		<a href="http://gravatar.com/emails" target="_blank">change</a>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>

<h1>All Users</h1>

<% if current_user.admin? %>
	<h2>Total Users: <%= @count %></h2>
<% end %>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
		<%= render user %>
	<% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>

<h1>Sign up</h1>
<div class="row">
	<div class="span6 offset4">

			<%= form_for(@user) do |f| %>
			<%= render "layouts/signup_error_messages" %>

				<%= f.label :name, "Display Name" %>
				<%= f.text_field :name %>

				<%= f.label :email, "Email (optional)" %>
				<%= f.text_field :email %>

				<%= f.label :password %>
				<%= f.password_field :password %>

				<%= f.label :password_confirmation, "Confirm Password" %>
				<%= f.password_field :password_confirmation%>

				<%= f.submit "Create my account", class:"btn btn-large btn-info signup" %>
			<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1><%= @user.name %></h1>

			<% if @user.email.blank? %>
				<h2><%= "Of unknown origin." %></h2>
			<% else %>
				<h2><%= @user.email %> </h2>
				<%= gravatar_for @user, size:100 %>
			<% end %>

			
		</section>
	</aside>
</div>